version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: singh-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - php_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: singh-phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    networks:
      - php_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

networks:
  php_net:
    driver: bridge